### ISSUE TITLE
Cannot cache files outside workspace

### ISSUE THREAD

**Issue by jessebye** [nienbo/cache-buildkite-plugin#23]
We have some golang projects that store their cache in docker at `/go/pkg/mod`. We can't find a good way to cache this folder using the plugin. If we set a path of `/go/pkg/mod`, the tar command removes the leading `/` and we end up with no files being cached. 

The only possible workaround is to copy the `/go/pkg/mod` folder into our working directory, but this is a bit janky.

**Comment by gencer** [comment]
Then we can omit this behavior and keep `/` as-is. However one thing makes me wonder: `restore`

How do tar know to restore absolute paths along with relative paths. We cannot keep storing absolute paths for relative paths as you might know so we need to somehow store that information to restore afterwards.

One thing might be to use metadata file along with cache. So cache plugin will read metadata file before any restore action then apply all restore points. When everything is over it will remove metadata file.

If I know correctly, Tar supports extracting single file so we can extract metadata first then read the contents from there. But I have no idea how performance impact happens. Need to test here.

Another option would be to create a symlink.

**Comment by KonstantinSimeonov** [comment]
Ran into the same problem with caching a pnpm store. Ended up using a symlink it in the current directory and reaching inside it with a glob in `paths`: `.pnpm-store/*`
