### ISSUE TITLE
--ignore-failed-read is not supported on macOS

### ISSUE THREAD

**Issue by djmarcin** [nienbo/cache-buildkite-plugin#5]
Attempting to use the tar plugin on a macOS machine fails:

tar: Option --ignore-failed-read is not supported
--
  | Usage:
  | List:    tar -tf <archive-filename>
  | Extract: tar -xf <archive-filename>
  | Create:  tar -cf <archive-filename> [filenames...]
  | Help:    tar --help
  | 🚨 Error: The plugin cache post-command hook exited with status 1

**Comment by gencer** [comment]
Hm.. It seems macOS has a very different `tar` syntax. Probably we should use `tar` without `--ignore-failed-read` on macOS. I'll throw a fix now.

I am thinking to make cache plugin very extensible by splitting code into pieces in its own files. So, for now a draft fix could be more than enough until I finally come up with a permanent solution.

**Comment by gencer** [comment]
Hi @djmarcin. Can you test against `master`?

```yaml
   - gencer/cache#master:
      ...
```

**Comment by gencer** [comment]
P.S.: Another option in here to use `--warning=no-file-changed`. I will surely include this one in next version.

If you want I can add this now so you can try on `master` with this option? But I'm unsure if this is the exact same behavior as actual option. So, might be needed to test before actually using it.

**Comment by djmarcin** [comment]
Yes -- I believe macOS uses bsdtar while linux uses GNU tar. Another workaround is using the rsync method on macOS.

I will test with master.

**Comment by djmarcin** [comment]
It looks like master works. 👍

**Comment by gencer** [comment]
Then let's make a new release for this. 👌

**Comment by gencer** [comment]
Released in `v2.0.9` 🎉.

P.S.: Don't forget to star ✨ this plugin if you like it.
