### ISSUE TITLE
Question on `rsync` backend

### ISSUE THREAD

**Issue by kyuhyunc** [nienbo/cache-buildkite-plugin#54]
Reading [this](https://github.com/nienbo/cache-buildkite-plugin#rsync),
I wasn't sure where BK agents would `rsync` files to.

in the example, it specifies a path that seems local to the agent, but `rsync` I thought would sync files to remote servers?
```
rsync:
          path: '/tmp/buildkite-cache' # Defaults to /tmp with v2.4.10+
```

**Comment by gencer** [comment]
Hi @kyuhyunc

This is primarily stay for backward compatibility. I'm not sure how many developers using rsync at these days BUT I'm sure there are.

You can expose your additional NFS/S3 disk to the VM as a disk and then rsync files to this volume. Or simply copy files from docker volume to local volume.

I'd probably -highly- recommend S3 or GC for your caches.

-Gencer.

**Comment by kyuhyunc** [comment]
that makes sense. thanks for input!
