### ISSUE TITLE
[QUESTION] Can you combine paths on checksum?

### ISSUE THREAD

**Issue by dep** [nienbo/cache-buildkite-plugin#56]
Is it possible to do something like this?

```
key: v1-assets-compile-cache-{{ checksum './{app|backdraft|client|components|test}' }}
```

**Comment by gencer** [comment]
Whoops. I absolutely missed this one.

First of all, sorry for late reply. I seriously missed this somehow 😱 

Second, Nope. Currently it is not possible. PRs welcome 🥳

**Comment by dep** [comment]
Thank you for the reply!

**Comment by gencer** [comment]
Temporarily closed. Please either reopen or just ping me If you still interested.
