### ISSUE TITLE
Failed S3 downloads not handled

### ISSUE THREAD

**Issue by bradleyayers** [nienbo/cache-buildkite-plugin#64]
We're using the S3 backend and experiencing an issue where corrupted .tar.gz files are being downloaded and extracted but tar dies because it can't decompress the file.

![image](https://github.com/nienbo/cache-buildkite-plugin/assets/105820/bb6e9efe-ea72-4711-879c-5e88843f041c)

I think it might be happening if the `aws s3 cp` command fails part way through (our files are ~400MB so perhaps the connection sometimes breaks), and then the script proceeds anyway to copy it into the local cache location:

https://github.com/nienbo/cache-buildkite-plugin/blob/9df04eba98325d751e108b5f1e9ec59d21205020/lib/backends/s3.bash#L115

Do we need something like a `|| exit 1`?

**Comment by gencer** [comment]
Perhaps, But I wonder how this works on different shells. I've seen some weird behaviors on different shells using boolean checks with `||`

I also commented on your PR.

**Comment by bradleyayers** [comment]
I've raised #65 to resolve this.

**Comment by nuzayets** [comment]
Thank you for patching it! Right as we've started to hit this issue, too. 

Could we get a patch version for this soon, pretty please? 🙏

**Comment by gencer** [comment]
Released as `v2.4.15` 🚀
