### ISSUE TITLE
Don't upload to S3 on local cache hit

### ISSUE THREAD

**Issue by franklin-ross** [nienbo/cache-buildkite-plugin#66]
When using S3 with `save-cache: true` and the local cache hits, we seem to then upload the local cache to S3 in the post-command step. That doesn't seem necessary as a local cache hit implies the same entry already exists in S3 and was previously downloaded.

![image](https://github.com/nienbo/cache-buildkite-plugin/assets/2695677/941fb531-57bf-4192-8a91-d3404523afab)

---

For comparison, here's what happens when the local cache misses and we download from S3, no 10 second upload:

![image](https://github.com/nienbo/cache-buildkite-plugin/assets/2695677/9e5fd46c-bc0b-4b92-948a-abd1e9387cd1)

**Comment by calvinbui** [comment]
i'm taking a look

**Comment by franklin-ross** [comment]
🎉
