### ISSUE TITLE
Feature request: Have a option to utilize cache in pre-command but not uploading back to s3 in post-command

### ISSUE THREAD

**Issue by Songyu-Wang** [nienbo/cache-buildkite-plugin#68]
Hello,

Thanks for the plugin! 
I am interested in using the `pr` arg to not upload new cache back to s3 in PRs. However, I still want to pull in existing cache from our protected branch since that is the baseline. 

Could we have a flag to `skip post command`?

**Comment by calvinbui** [comment]
i'd like to work on this, but I've been going back and forth on the best approach @gencer.

I'd like some way to also skip uploading the cache when not on the default branch (e.g. master/main), regardless if it's a PR (`pr: false`).

I have the following solutions:

1. replace `always` or `pr` with `upload-cache`. this would be a breaking change, so I could add the key as is for now, have it default to `true` and skip over the other options if it's not set.
    - `upload-cache: true`: normal behaviour (i.e `pr: true`)
    - `upload-cache: default-branch`: only upload cache when working on the default branch (main/master) (similar to `pr: false`)
    - `upload-cache: false`: skip uploading entirely
 
1. add a `upload-branches` (or similar worded) list that users can specify what branches are should to upload caches

1. add a `upload-only-on-default-branch` (or similar worded) bool, which does exactly as it says.

Each option would solve this issue (and my own need for skipping non-default branches).

**Comment by gencer** [comment]
Awesome @calvinbui!

I saw the PR and there is nothing to add on my side. Looks solid.
